
name: "adam"
learning_rate: 0.001
weight_decay: 0.0001
betas: [0.9, 0.999]
eps: 1.0e-8
amsgrad: false

scheduler:
  name: "cosine"
  enabled: true
  T_max: 100  # max_epochs (se sobrescribe dinámicamente)
  eta_min: 1.0e-6 