

name: "sgd"
learning_rate: 0.01  # SGD necesita LR más alto
momentum: 0.9
weight_decay: 0.0001
nesterov: true

scheduler:
  name: "step"
  enabled: true
  
  # Parámetros para StepLR
  step_size: 30
  gamma: 0.1
  